apartment/apartment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf.urls import re_path
from myapp.views import *

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path('^users/', include('users.urls', namespace = "users")),
    re_path('^$', HomeView.as_view(), name = 'index'),
    re_path('^index/', HomeView.as_view(), name = 'index'),
    re_path('^student/', StudentListView.as_view(), name = 'student'),
    re_path('^room/', RoomListView.as_view(), name = 'room'),
    re_path('^electric_charge/', ElectricChargeView.as_view(), name = 'electric_charge'),
    re_path('^water_charge/', WaterChargeView.as_view(), name = 'water_charge'),
    re_path('^sanitation/', SanitationListView.as_view(), name = 'sanitation'),
    re_path('^device/', DeviceListView.as_view(), name = 'device'),
    re_path('^device_sent_record/', DeviceSentRecordListView.as_view(), name = 'device_sent_record'),
    re_path('^rule/', RuleListView.as_view(), name = 'rule'),
]

apartment/apps/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__version__ = '3.0.3'
from django.conf.urls import url
from django.urls import path
from .views import LoginView, RegisterView, LogoutView


app_name = 'users'


urlpatterns = [
    path(r'login/', LoginView.as_view(), name="login"),
    path(r'logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
]

apartment/apps/myapp/models.py
from django.db import models

# Create your models here.


class RoomModel(models.Model):
    room_no = models.CharField(verbose_name="room_id", max_length=100, unique=True)
    location = models.CharField(verbose_name="region", max_length=100,default=None)
    sex = models.IntegerField(verbose_name='sex', choices=((0, 'male'), (1, 'female')))
    size = models.IntegerField(verbose_name="bed id", choices=((0, '4people'), (1, '6people')))
    electric_charge = models.IntegerField(verbose_name="remaining_electricity($)")
    water_charge = models.IntegerField(verbose_name="remaining_water($)")

    class Meta:
        verbose_name = "room_information"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.location + self.room_no


    
  
class StudentModel(models.Model):
    name = models.CharField(verbose_name='name',max_length=100)
    sex = models.IntegerField(verbose_name='sex', choices=((0, 'male'), (1, 'female')), default=0)
    grade = models.CharField(verbose_name="grade", max_length=100)
    profession = models.CharField(verbose_name="major", max_length=255, default=None)
    phone = models.CharField(verbose_name="phone", max_length=11)
    room = models.ForeignKey(RoomModel, verbose_name="room_id", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "user_information"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SanitationModel(models.Model):
    """
    hygiene record
    """
    room = models.ForeignKey(RoomModel, verbose_name="room_id", on_delete=models.CASCADE)
    target_date = models.DateField(verbose_name="date")
    score = models.IntegerField(verbose_name="score")

    class Meta:
        verbose_name = "hygiene_information"
        verbose_name_plural = verbose_name


class DeviceModel(models.Model):
    """
    device
    """
    name = models.CharField(verbose_name="device_name", max_length=100)
    status = models.IntegerField(verbose_name="device_status", choices=((0, "exist"), (1, "lend")))

    class Meta:
        verbose_name = "device_information"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class DeviceSentRecordModel(models.Model):
    """
    device check record
    """
    device = models.ForeignKey(DeviceModel, verbose_name="device", related_name='sent_record', on_delete=models.CASCADE)
    room = models.ForeignKey(RoomModel, verbose_name="dorm", on_delete=models.CASCADE)
    person = models.ForeignKey(StudentModel, verbose_name="renter", on_delete=models.CASCADE)
    borrow_time = models.DateTimeField(verbose_name="lease_time")
    send_time = models.DateTimeField(verbose_name="return_time", blank=True)

    class Meta:
        verbose_name = "device_lending_record"
        verbose_name_plural = verbose_name


class RuleModel(models.Model):
    """
    violation record to save information
    """
    rule_type = models.IntegerField(verbose_name="violation_type", choices=((0, 'roommateContradiction'), (1, 'drunk'), (2, 'damagePublicProperty'), (3, 'smoke'), (4, 'other')))
    room = models.ForeignKey(RoomModel, verbose_name="dorm", on_delete=models.CASCADE)
    person = models.ForeignKey(StudentModel, verbose_name="person", on_delete=models.CASCADE)
    record_time = models.DateTimeField(verbose_name="time")
    remark = models.CharField(verbose_name="comment", max_length=512)

    class Meta:
        verbose_name = "violation_record"
        verbose_name_plural = verbose_name

apartment/templates/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Apartment Management System</title>
        <meta name="description" content="">
        <meta name="keywords" content="index">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="{% static  'assets/i/favicon.png'%}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'assets/i/app-icon72x72@2x.png' %}">
        <meta name="apple-mobile-web-app-title" content="Amaze UI" />
        <link rel="stylesheet" href="{% static 'assets/css/amazeui.min.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/admin.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">
        <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body data-type="generalComponents">
        <header class="am-topbar admin-header">

            <div class="am-topbar-brand">
                <h4 href="javascript:;" class="tpl-logo">
                    Apartment Management System
                </h4>
            </div>
            <div class="am-icon-list tpl-header-nav-hover-ico am-fl am-margin-right">
            </div>
            <div class="am-collapse am-topbar-collapse" id="topbar-collapse">
                <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list tpl-header-list">
                    <li><a>{{ request.user }}</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>
                </ul>
            </div>
        </header>
        <div class="tpl-page-container tpl-page-header-fixed">
            <div class="tpl-left-nav tpl-left-nav-hover">
                <div class="tpl-left-nav-title">Navigation</div>
                <div class="tpl-left-nav-list">
                    <ul class="tpl-left-nav-menu">
                        <li class="tpl-left-nav-item">
                            <a href="/index"  {% if request.path == '/index/' %} class="nav-link active" {% else %} class="nav-link tpl-left-nav-link-list" {% endif %}>
                                <i class="am-icon-home"></i>
                                <span>Home</span>
                            </a>
                        </li>
                        <li class="tpl-left-nav-item">
                            <a href="/student" {% if request.path == '/student/' %} class="nav-link active" {% else %} class="nav-link tpl-left-nav-link-list" {% endif %}>
                                <i class="am-icon-comment"></i>
                                <span>User Information</span>
                            </a>
                        </li>

                        <li class="tpl-left-nav-item">
                            <a href="/room" {% if request.path == '/room/' %} class="nav-link active" {% else %} class="nav-link tpl-left-nav-link-list" {% endif %}>
                                <i class="am-icon-bar-chart"></i>
                                <span>Apartment Information</span>
                            </a>
                        </li>

                        <li class="tpl-left-nav-item">
                            <a href="/sanitation" {% if request.path == '/sanitation/' %} class="nav-link active" {% else %} class="nav-link tpl-left-nav-link-list" {% endif %}>
                                <i class="am-icon-github-square"></i>
                                <span>Hygiene</span>
                            </a>
                        </li>
                        <li class="tpl-left-nav-item">
                            <a href="/device" {% if request.path == '/device/' %} class="nav-link active" {% else %} class="nav-link tpl-left-nav-link-list" {% endif %}>
                                <i class="am-icon-feed"></i>
                                <span>Device Record</span>
                            </a>
                        </li>
                        <li class="tpl-left-nav-item">
                            <a href="/rule" {% if request.path == '/rule/' %} class="nav-link active" {% else %} class="nav-link tpl-left-nav-link-list" {% endif %}>
                                <i class="am-icon-certificate"></i>
                                <span>Violation Record</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
            <div class="tpl-content-wrapper">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <script src="/static/assets/js/jquery.min.js"></script>
        <script src="/static/assets/js/amazeui.min.js"></script>
        <script src="/static/assets/js/app.js"></script>
    </body>
</html>

apartment/templates/device.html
{% extends 'base.html' %}
{% block content %}
<div class="tpl-content-wrapper">
    <div class="tpl-portlet-components">
        <div class="portlet-title">
            <div class="caption font-green bold">
                <span class="am-icon-code">Device Record</span>
            </div>
            <div class="tpl-portlet-input tpl-fz-ml">
                <div class="portlet-input input-small input-inline">
                    <form action="{% url 'room' %}" method="post" class="sidebar-form">
                        <div class="am-input-group">
                            <input type="text" class="am-form-field" placeholder="search..." name="q">
                            <span class="am-input-group-btn">
                                <input class="am-btn am-btn-default" type="submit"><span class="am-icon-search"></span></input>
                            </span>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>


        <div class="tpl-block">
            <div class="am-g">
                <div class="am-u-sm-12">
                        <table class="am-table am-table-striped am-table-hover table-main">
                        <thead>
                           <tr>
                                <th class="table-id">id</th>
                                <th class="table-title">device name</th>
                                <th class="table-date am-hide-sm-only">device status</th>
                                <th class="table-title">operation</th>
                           </tr>
                        </thead>
                        <tbody>
                        {% for item in paginator.object_list %}
                            <tr>
                                <td>{{item.id}}</td>
                                <td>{{item.name}}</td>
                                <td>{{item.get_status_display }}</td>
                                <td><a href="{% url 'device_sent_record' %}?device_id={{item.id}}">Check Record</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                        <hr>
                         <div style="width: 80%;margin: auto">
                    <ul class="pagination pagination-lg">
                    {% if paginator.has_previous %}
                        <li>
                            <a href="{% url 'device' %}?page={{ paginator.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for number in paginator.paginator.pager_num_range %}
                        {% if number == paginator.number %}
                            <li class="active"><a href="{% url 'device' %}?page={{ number }}">{{ number }}</a></li>
                        {% else %}
                            <li><a href="{% url 'device' %}?page={{ number }}" >{{ number }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if paginator.has_next %}
                        <li>
                            <a href="{% url 'device' %}?page={{ paginator.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% endif %}
                    </ul>
                </div>

                </div>

            </div>
        </div>
        <div class="tpl-alert"></div>
    </div>
</div>
{% endblock %}

apartment/templates/electric_charge.html
{% extends 'base.html' %}
{% block content %}
<div class="tpl-content-wrapper">
    <div class="tpl-portlet-components">
        <div class="portlet-title">
            <div class="caption font-green bold">
                <span class="am-icon-code">Electric Charge</span>
            </div>
        </div>

        <form class="tpl-block" method="post" action="{% url 'electric_charge' %}">
            <div class="am-g">
                You charge for {{ room.location  }}  {{ room.room_no }}
                <input type="text" style="width: 50px;height: 30px;color: #2a6496" name="charge">$
                <input type="text" style="display: none" value="{{ room.id }}" name="room_id">
                <p><input type="submit" style="color: #2a6496" class="button"><p>
            </div>
            {% csrf_token %}
            </form>
        </div>
        <div class="tpl-alert"></div>
    </div>
</div>
{% endblock %}

apartment/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="tpl-portlet-components">
        <div class="portlet-title">
            <h1 align="center">Welcome to <span style="font-size: 35px;color: #0e90d2">Apartment</span>&nbsp;&nbsp;Management System!</h1>
        </div>
        <div class="tpl-block">
            <div class="am-g">
                <div class="am-u-sm-12">
                </div>
            </div>
        </div>
        <div class="tpl-alert"></div>
    </div>
{% endblock %}

apartment/templates/room.html
{% extends 'base.html' %}
{% block content %}
<div class="tpl-content-wrapper">
    <div class="tpl-portlet-components">
        <div class="portlet-title">
            <div class="caption font-green bold">
                <span class="am-icon-code">Apartments</span>
            </div>
            <div class="tpl-portlet-input tpl-fz-ml">
                <div class="portlet-input input-small input-inline">
                    <form action="{% url 'room' %}" method="post" class="sidebar-form">
                        <div class="am-input-group">
                            <input type="text" class="am-form-field" placeholder="search..." name="q">
                            <span class="am-input-group-btn">
                                <input class="am-btn am-btn-default" type="submit"><span class="am-icon-search"></span></input>
                            </span>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>

            </div>
        </div>

        <div class="tpl-block">
            <div class="am-g">
                <div class="am-u-sm-12">
                        <table class="am-table am-table-striped am-table-hover table-main">
                        <thead>
                           <tr>
                                <th class="table-id">id</th>
                                <th class="table-title">room id</th>
                                <th class="table-title">region</th>
                                <th class="table-type">sex</th>
                                <th class="table-title">type</th>
                                <th class="table-date am-hide-sm-only">remaining electric ($)</th>
                                <th class="table-date am-hide-sm-only">remaining water ($)</th>
                                <th class="table-title">operation</th>
                           </tr>
                        </thead>
                        <tbody>
                        {% for item in paginator.object_list %}
                            <tr>
                                <td>{{item.id}}</td>
                                <td>{{item.room_no}}</td>
                                <td>{{item.location}}</td>
                                <td>{{item.get_sex_display }}</td>
                                <td>{{item.get_size_display}}</td>
                                <td>{{item.electric_charge}}</td>
                                <td>{{item.water_charge}}</td>
                                <td><a href="{% url 'electric_charge' %}?room_id={{item.id}}">charge electricity</a>
                                    /<a href="{% url 'water_charge' %}?room_id={{item.id}}">charge water</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                        <hr>
                         <div style="width: 80%;margin: auto">
                    <ul class="pagination pagination-lg">
                    {% if paginator.has_previous %}
                        <li>
                            <a href="{% url 'room' %}?page={{ paginator.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for number in paginator.paginator.pager_num_range %}
                        {% if number == paginator.number %}
                            <li class="active"><a href="{% url 'room' %}?page={{ number }}">{{ number }}</a></li>
                        {% else %}
                            <li><a href="{% url 'room' %}?page={{ number }}" >{{ number }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if paginator.has_next %}
                        <li>
                            <a href="{% url 'room' %}?page={{ paginator.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% endif %}
                    </ul>
                </div>

                </div>

            </div>
        </div>
        <div class="tpl-alert"></div>
    </div>
</div>
{% endblock %}

apartment/templates/rule.html
{% extends 'base.html' %}
{% block content %}
<div class="tpl-content-wrapper">
    <div class="tpl-portlet-components">
        <div class="portlet-title">
            <div class="caption font-green bold">
                <span class="am-icon-code">Violation Record</span>
            </div>
        </div>

        <div class="tpl-block">
            <div class="am-g">
                <div class="am-u-sm-12">
                        <table class="am-table am-table-striped am-table-hover table-main">
                        <thead>
                           <tr>
                                <th class="table-id">id</th>
                                <th class="table-title">room id</th>
                               <th class="table-type">type</th>
                                <th class="table-title">person</th>
                                <th class="table-title">time</th>
                                <th class="table-title">comment</th>
                           </tr>
                        </thead>
                        <tbody>
                        {% for item in paginator.object_list %}
                            <tr>
                                <td>{{item.id}}</td>
                                <td>{{item.room}}</td>
                                <td>{{item.get_rule_type_display}}</td>
                                <td>{{item.person }}</td>
                                <td>{{item.record_time}}</td>
                                <td>{{item.remark}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                        <hr>
                         <div style="width: 80%;margin: auto">
                    <ul class="pagination pagination-lg">
                    {% if paginator.has_previous %}
                        <li>
                            <a href="{% url 'rule' %}?page={{ paginator.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for number in paginator.paginator.pager_num_range %}
                        {% if number == paginator.number %}
                            <li class="active"><a href="{% url 'rule' %}?page={{ number }}">{{ number }}</a></li>
                        {% else %}
                            <li><a href="{% url 'rule' %}?page={{ number }}" >{{ number }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if paginator.has_next %}
                        <li>
                            <a href="{% url 'rule' %}?page={{ paginator.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% endif %}
                    </ul>
                </div>

                </div>

            </div>
        </div>
        <div class="tpl-alert"></div>
    </div>
</div>
{% endblock %}

apartment/templates/student.html
{% extends 'base.html' %}
{% block content %}
<div class="tpl-content-wrapper">
    <div class="tpl-portlet-components">
        <div class="portlet-title">
            <div class="caption font-green bold">
                <span class="am-icon-code">User Information</span>
            </div>
            <div class="tpl-portlet-input tpl-fz-ml">
                <div class="portlet-input input-small input-inline">
                    <form action="{% url 'student' %}" method="post" class="sidebar-form">
                        <div class="am-input-group">
                            <input type="text" class="am-form-field" placeholder="search..." name="q">
                            <span class="am-input-group-btn">
                                <input class="am-btn am-btn-default" type="submit"><span class="am-icon-search"></span></input>
                            </span>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>

            </div>
        </div>

        <div class="tpl-block">
            <div class="am-g">
                <div class="am-u-sm-12">
                        <table class="am-table am-table-striped am-table-hover table-main">
                        <thead>
                           <tr>
                                <th class="table-id">User ID</th>
                                <th class="table-title">name</th>
                                <th class="table-type">gender</th>
                                <th class="table-title">grade</th>
                                <th class="table-date am-hide-sm-only">major</th>
                                <th class="table-date am-hide-sm-only">phone</th>
                                <th class="table-title">room id</th>
                           </tr>
                        </thead>
                        <tbody>
                        {% for item in paginator.object_list %}
                            <tr>
                                <td>{{item.id}}</td>
                                <td>{{item.name}}</td>
                                <td>{{item.get_sex_display }}</td>
                                <td>{{item.grade}}</td>
                                <td>{{item.profession}}</td>
                                <td>{{item.phone}}</td>
                                <td>{{item.room}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                        <hr>
                         <div style="width: 80%;margin: auto">
                    <ul class="pagination pagination-lg">
                    {% if paginator.has_previous %}
                        <li>
                            <a href="{% url 'student' %}?page={{ paginator.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for number in paginator.paginator.pager_num_range %}
                        {% if number == paginator.number %}
                            <li class="active"><a href="{% url 'student' %}?page={{ number }}">{{ number }}</a></li>
                        {% else %}
                            <li><a href="{% url 'student' %}?page={{ number }}" >{{ number }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if paginator.has_next %}
                        <li>
                            <a href="{% url 'student' %}?page={{ paginator.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                    {% endif %}
                    </ul>
                </div>

                </div>

            </div>
        </div>
        <div class="tpl-alert"></div>
    </div>
</div>
{% endblock %}

apartment/templates/water_charge.html
{% extends 'base.html' %}
{% block content %}
<div class="tpl-content-wrapper">
    <div class="tpl-portlet-components">
        <div class="portlet-title">
            <div class="caption font-green bold">
                <span class="am-icon-code">Water Charge</span>
            </div>
        </div>

        <form class="tpl-block" method="post" action="{% url 'water_charge' %}">
            <div class="am-g">
                You charge for {{ room.location  }}  {{ room.room_no }}
                <input type="text" style="width: 50px;height: 30px;color: #2a6496" name="charge">$
                <input type="text" style="display: none" value="{{ room.id }}" name="room_id">
                <p><input type="submit" style="color: #2a6496" class="button"><p>
            </div>
            {% csrf_token %}
            </form>
        </div>
        <div class="tpl-alert"></div>
    </div>
</div>
{% endblock %}