apartment/apartment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf.urls import re_path
from myapp.views import *

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path('^users/', include('users.urls', namespace = "users")),
    re_path('^$', HomeView.as_view(), name = 'index'),
    re_path('^index/', HomeView.as_view(), name = 'index'),
    re_path('^student/', StudentListView.as_view(), name = 'student'),
    re_path('^room/', RoomListView.as_view(), name = 'room'),
    re_path('^electric_charge/', ElectricChargeView.as_view(), name = 'electric_charge'),
    re_path('^water_charge/', WaterChargeView.as_view(), name = 'water_charge'),
    re_path('^sanitation/', SanitationListView.as_view(), name = 'sanitation'),
    re_path('^device/', DeviceListView.as_view(), name = 'device'),
    re_path('^device_sent_record/', DeviceSentRecordListView.as_view(), name = 'device_sent_record'),
    re_path('^rule/', RuleListView.as_view(), name = 'rule'),
]

apartment/apps/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__version__ = '3.0.3'
from django.conf.urls import url
from django.urls import path
from .views import LoginView, RegisterView, LogoutView


app_name = 'users'


urlpatterns = [
    path(r'login/', LoginView.as_view(), name="login"),
    path(r'logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
]

apartment/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import make_password
# Create your models here.

# userprofile model
class UserProfile(AbstractUser):
    mobile = models.CharField(max_length=11, null=True, blank=True)
    image = models.ImageField(upload_to="images/%Y/%m", default=u"images/default.jpg", max_length=100, blank = True)

    
    class Meta:
        verbose_name = "user_information"
        verbose_name_plural = verbose_name

        
    def save(self, *args, **kwargs):
        if self.password.find("pbkdf2_sha256$") ==-1:
            self.password = make_password(self.password)
        return super(UserProfile, self).save(*args, **kwargs)

    
    def __unicode__(self):
        return self.username






apartment/apps/users/views.py
import json
from django.shortcuts import render, reverse
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from .models import UserProfile
from .form import LoginForm, RegisterForm
from django.contrib.auth.hashers import make_password
# Create your views here.


class CustomBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            username = request.POST.get("username", "")
            password = request.POST.get("password", "")
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


class LoginView(View):
    def get(self, request):
        return render(request, "users/login.html")

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():

            user = authenticate(request)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return render(request, "users/login.html", {"msg": "username or password is incorrect！"})
        else:
            return render(request, "users/login.html", {"login_form": login_form})

        
class LogoutView(View):
    """
    logout
    """
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse("users:login"))
  

class RegisterView(View):

    def get(self, request):
        return render(request, "users/register.html")

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user_name = request.POST.get("username", "")
            email = request.POST.get("email", "")
            if UserProfile.objects.filter(Q(username=user_name) | Q(email=email)):
                return HttpResponse(json.dumps({"status": -1, "msg": "user already existed"}), content_type = 'application/json')
            pass_word = request.POST.get("password", "")
            user_profile = UserProfile()
            user_profile.username = user_name
            user_profile.email = email
            user_profile.is_active = True
            user_profile.password = make_password(pass_word)
            user_profile.save()
            return render(request, "users/register.html", {"msg": "Successful！<a href='/users/login' class='am-btn am-btn-default'>sign in</a>"})
        else:
            msg = ""
            for key, error in register_form.errors.items():
                msg += "<p>%s</p>" % error
            return render(request, "users/register.html", {"msg": msg})

apartment/templates/users/login.html
{% load static %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
        <title>Login</title>
        <link rel="stylesheet" href="/static/assets/css/amazeui.min.css" />
        <link rel="stylesheet" href="/static/assets/css/admin.css">
        <link rel="stylesheet" href="/static/assets/css/app.css">
        <style type="text/css">
            .error{
                background: #fb8344;
                color:#fff !important;
                text-align: center;
                line-height: 40px !important;
                margin:10px 0;}
        </style>
    </head>

    <body data-type="login">
        <div class="am-g myapp-login">
            <div class="myapp-login-logo-block  tpl-login-max">
                <div class="myapp-login-logo-text">
                    <div class="myapp-login-logo-text">
                        Apartment Management System<span> sign in</span> <i class="am-icon-skyatlas"></i>
                    </div>
                </div>
                <div class="am-u-sm-10 login-am-center">
                    <form class="am-form" method="post" action="{% url 'users:login' %}">
                        <fieldset>
                            <div class="am-form-group">
                                <input type="text" class="" name="username" id="doc-ipt-email-1" placeholder="username">
                            </div>
                            <div class="am-form-group">
                                <input type="password" name="password" class="" id="doc-ipt-pwd-1" placeholder="password">
                            </div>
                            {% csrf_token %}
                            <p>
                                <button type="submit" class="am-btn am-btn-default">sign in</button>

                            </p>
                            <p>
                                <a class="am-btn am-btn-default" href="{% url 'users:register'%}">sign up</a>
                            </p>
                        </fieldset>
                        <div class="error btns" id="jsEmailTips">{{ msg | safe }}</div>
                    </form>
                </div>
            </div>
        </div>
        <script src="/static/assets/js/jquery.min.js"></script>
        <script src="/static/assets/js/amazeui.min.js"></script>
        <script src="/static/assets/js/app.js"></script>
    </body>
</html>

apartment/templates/users/register.html
{% load static %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
        <title>Register</title>
        <link rel="stylesheet" href="/static/assets/css/amazeui.min.css" />
        <link rel="stylesheet" href="/static/assets/css/admin.css">
        <link rel="stylesheet" href="/static/assets/css/app.css">
        <style type="text/css">
            .error{
                background: #fb8344;
                color:#fff !important;
                text-align: center;
                line-height: 40px !important;
                margin:10px 0;}
        </style>
    </head>

    <body data-type="login">
        <div class="am-g myapp-login">
            <div class="myapp-login-logo-block  tpl-login-max">
                <div class="myapp-login-logo-text">
                    <div class="myapp-login-logo-text">
                        Apartment Management System<span> Register</span> <i class="am-icon-skyatlas"></i>
                    </div>
                </div>
                <div class="am-u-sm-10 login-am-center">
                    <form class="am-form" method="post" action="{% url 'users:register' %}">
                        <fieldset>
                            <div class="am-form-group">
                                <input type="text" class="" name="username" id="doc-ipt-email-1" placeholder="username">
                            </div>
                            <div class="am-form-group">
                                <input type="email" name="email" class="" id="doc-ipt-email-1" placeholder="email">
                            </div>
                            <div class="am-form-group">
                                <input type="password" name="password" class="" id="doc-ipt-pwd-l" placeholder="password">
                            </div>
                            {% csrf_token %}
                            <p><button type="submit" class="am-btn am-btn-default">sign up</button></p>
                        </fieldset>
                        <div class="error btns" id="jsEmailTips">{{ msg | safe }}</div>

                    </form>
                </div>
            </div>
        </div>
        <script src="/static/assets/js/jquery.min.js"></script>
        <script src="/static/assets/js/amazeui.min.js"></script>
        <script src="/static/assets/js/app.js"></script>
    </body>
</html>